name: Send APOD

on:
  schedule:
    # Winter (Octâ€“Dec)
    - cron: "30 9 * * *"

  workflow_dispatch:   # allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install requests

    - name: Run APOD script
      env:
        NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python apod.py
